/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ef6244ea-79d0-491b-be02-a901ebc66d55",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_iCIX0hp6o",
    "aws_user_pools_web_client_id": "2fkjsfcqhvrbghe3g0fosjsiiu",
    "oauth": {},
};

export default awsmobile;